### ISSUE TITLE
[MQ Error] 마약입고 관련

### ISSUE THREAD

**Issue by riatree-whale** [riatree-whale/ez_pharmacy#11]
### **마약류 구매보고**
> 문의병원 : 국립마산병원 
> 문의일자 : 2024년 01월 09일 
> 약품코드 : IDZP 
> 입고수량 : 20개 

**사건경위** 
2024-01-05 18:00 사용자가 ERP에서 약품 입고  
- Mediro 오류 (원인 : 일련번호 기재오류 ) 

2024-01-08 JD업체로부터 데이터처리 요청 
- 일련번호 임의값 입력 후 전송 데이터처리 
- NIMS보고 및 입고처리 완료 

2024-01-09 JD 오류내용 수정 

데이터처리 
```
select * from nimsinterface_body;
select * from druginventory_drugstock;
```

**Comment by riatree** [comment]
2024-01-10 문의 답변완료
